---
name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [master, main]

jobs:
  job1:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java 17 temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build project using maven
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t vassilb/myapp .
      - name: Publish image to docker hub
        run: docker push vassilb/myapp:latest

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,quickview
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true