---
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  job1:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint Code Base
      uses: dbelyaev/action-checkstyle@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        checkstyle_config: google_checks.xml
        level: warning

  job2:
    name: Checking for secrets
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Run Yelp's detect-secrets
      uses: RobertFischer/detect-secrets-action@v2.0.0
    - name: Commit back .secrets.baseline (if it was missing)
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"

  job3:
    name: SonaCloud scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CatInTheBag_devops-final-project
