---
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  testing:
    needs: secrets
    name: run unit tests on Java 17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17 temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Run Maven clean test jobs
        run : mvn -f pom.xml clean test
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the target directory
        run: ls -la target

  linting:
    needs: testing
    name: Lint code base with checkstyle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint Code Base
      uses: dbelyaev/action-checkstyle@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-check
        checkstyle_config: google_checks.xml
        level: warning

  secrets:
    #for testing purpose
    #needs: linting
    name: Checking for secrets using git-secrets
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: install git-secrets
      run: |
        wget https://github.com/awslabs/git-secrets
        cd git-secrets
        ls -la
        echo $PWD
        sudo make install

    - name: Show contents of the current working directory
      run: ls -la

    - name: Scan for secrets
      run: git secrets --scan -r

    - name: Check for secrets
      run: git secrets --scan-history


  vulnerabilities:
    needs: secrets
    name: SonaCloud scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CatInTheBag_devops-final-project
