---
name: CI/CD

#events
on:
  workflow_dispatch:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  job1:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # super-linter needs the full git history to get the
        # list of files that changed across commits
        fetch-depth: 0

      ################################
      # Run Linter against code base #
      ###############################
    - name: Lint Code Base
      uses: super-linter/super-linter@v5.7.2
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_JAVA: true
        VALIDATE_YAML: true
        DEFAULT_BRANCH: master
        LINTER_RULES_PATH: configs/
        DISABLE_ERRORS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job2:
    name: second job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4