---
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  job1:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Lint Code Base
      uses: super-linter/super-linter@v5.7.2
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVA: true
        VALIDATE_YAML: true
        DEFAULT_BRANCH: master
        LINTER_RULES_PATH: configs/
        #disabled for testing purpose
        DISABLE_ERRORS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job2:
    name: Checking for secrets
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Secret Scanner
      uses: secret-scanner/action@0.0.2